### ISSUE TITLE
Missing "drill files"?

### ISSUE THREAD

**Issue by doctea** [mzourack/TRIGGER-WARNING#1]
Hi, thanks for your work and for sharing this, looks great!

I uploaded the provided .zip files to pcbway, but they have got in touch to say:-
"Your file lacks of the drill file,please check it .（Your drill files are empty.）
If you missing the drill file, please offer complete sets of new file with correct drill layer, Excellon format or .TXT format."

This is one of my first attempts at getting PCBs made so I don't know if I'm doing something wrong?  Any advice please?

Thanks

**Comment by mzourack** [comment]
Hey there.
I have no experience with PCBway, so I do not know what file type they require. You could definitely look that up and export from the files in the correct format (just download Kicad, it is free).
Instead of PCBway, I use jlcpcb for all my pcb needs. The gerbers i provided in the repository are 100% JLCPCB ready, so you can also just use that service instead :)
Let me know if you need any help.

**Comment by doctea** [comment]
Alright, thanks :D
